### ISSUE TITLE
Stores documentation unclear to me

### ISSUE THREAD

**Issue by mixmix** [flumedb/flumeview-reduce#5]
What's the default? (if I don't do the injection of a store thing)
`store/index.js` has some weird logic I've not seen before : `if (false && someThing)`
Looks like the default is `flumeview-reduce/store/fs`

in the Example code, `Store` is defined, making the example a little hard to understand.

Is the example in the Store section actually two different stores? (I don't know what a remote store is so valuable because I'm new here)

**Comment by dominictarr** [comment]
`false && anything` always evaluates to false, so it means that branch of the if never happens. it's basically a like a comment... debug artifact. fixed in 1.3.11

a remote store was an idea to replicate the view into the browser (etc) you'd first copy the current state of the view, and then stream the changes since then. (unless you are so far out of date that it's cheaper to just send the whole thing again) I was exploring this way but then realized that it was actually faster (on initial load) to just query each time (for small queries) which was the way I went for patchless. So currently there is nothing that uses this remote idea, but maybe it's useful for something else one day.

**Comment by mixmix** [comment]
Thanks for that context.

This is an example of code that looks dead (and is) but has a story so
shouldn't be removed.
Can we copy this sort here in as a comment to help other travelers?

**Comment by dominictarr** [comment]
how about a link back to this issue?

**Comment by christianbundy** [comment]
I think the actual problem code was removed (I don't see it in [fs.js](https://github.com/flumedb/flumeview-reduce/blob/master/store/fs.js)). Is this good to close?
